# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from move_grip/MoveGripARMessage.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MoveGripARMessage(genpy.Message):
  _md5sum = "6d5beb0266670a57045cd6010a8b23d3"
  _type = "move_grip/MoveGripARMessage"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 object_robot_angle
float32 wall_object_angle
float64 timestamp
"""
  __slots__ = ['object_robot_angle','wall_object_angle','timestamp']
  _slot_types = ['float32','float32','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_robot_angle,wall_object_angle,timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveGripARMessage, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.object_robot_angle is None:
        self.object_robot_angle = 0.
      if self.wall_object_angle is None:
        self.wall_object_angle = 0.
      if self.timestamp is None:
        self.timestamp = 0.
    else:
      self.object_robot_angle = 0.
      self.wall_object_angle = 0.
      self.timestamp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2fd().pack(_x.object_robot_angle, _x.wall_object_angle, _x.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.object_robot_angle, _x.wall_object_angle, _x.timestamp,) = _get_struct_2fd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2fd().pack(_x.object_robot_angle, _x.wall_object_angle, _x.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.object_robot_angle, _x.wall_object_angle, _x.timestamp,) = _get_struct_2fd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2fd = None
def _get_struct_2fd():
    global _struct_2fd
    if _struct_2fd is None:
        _struct_2fd = struct.Struct("<2fd")
    return _struct_2fd
